language: ruby
rvm:
- 2.2
script: bundle exec jekyll build && bundle exec htmlproof ./_site
branches:
  only:
  - master
  - travis-integration
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
