# Site settings
title: Chaos Darmstadt e.V.
tagline: Ihre verläßliche CCC-Vertretung in Südhessen
email: info@chaos-darmstadt.de
description: > # this means to ignore newlines until "baseurl:"
  Hier bitte eine aussagekräftige Beschreibung für Google & Co., damit man euch
  auch finden kann und so weiter.
baseurl: /
url: "http://www.chaos-darmstadt.de"

# Build settings
markdown: kramdown

permalink: ":year/:title.html"

sass:
    sass_dir: _sass
    style: :compressed
