# Site settings
title: Chaos Darmstadt e.V.
tagline: Ihre verl채ssliche CCC-Vertretung in S체dhessen
email: info@chaos-darmstadt.de
# version with '>' for newline ignore didn't work very well
description: Darmst채dter Erfahrungs-Austauschkreis des Chaos Computer Club, Hackspace und Hochschulgruppe an der TU Darmstadt
baseurl: /
exclude: [vendor]
url: "https://chaos-darmstadt.de"

# Build settings
markdown: kramdown

permalink: ":year/:title.html"

sass:
    sass_dir: _sass
    style: :compressed

nav_links:
    left:
        News: '/'
        Hackspace: '/hackspace.html'
        Termine: '/termine.html'
        Freifunk: '/freifunk.html'
        WizardsOfDos: '/wizardsofdos.html'
        C-Radar: '/c-radar.html'
    right:
        Kontakt: '/kontakt.html'
        Unterst체tzen: '/unterstuetzen.html'
