# Site settings
title: Chaos Darmstadt e.V.
tagline: Lorem Ipsum dolor sid ist fett.
email: info@chaos-darmstadt.de
description: > # this means to ignore newlines until "baseurl:"
  Hier bitte eine aussagekräftige Beschreibung für Google & Co., damit man euch
  auch finden kann und so weiter.
baseurl: /
url: "http://www.chaos-darmstadt.de"

# Build settings
markdown: kramdown
