# Site settings
title: Chaos Darmstadt e.V.
tagline: Ihre verl채ssliche CCC-Vertretung in S체dhessen
email: info@chaos-darmstadt.de
description: > # this means to ignore newlines until "baseurl:"
  Hier bitte eine aussagekr채ftige Beschreibung f체r Google & Co., damit man euch
  auch finden kann und so weiter.
baseurl: /
url: "http://www.chaos-darmstadt.de"

# Build settings
markdown: kramdown

permalink: ":year/:title.html"

sass:
    sass_dir: _sass
    style: :compressed

nav_links:
    left:
        News: '/news.html'
        Hackspace: '/hackspace.html'
        Freifunk: '/freifunk.html'
        PyStaDa: '/pystada.html'
        C-Radar: '/c-radar.html'
    right:
        Wiki: '/wiki.html'
        Kontakt: '/kontakt.html'