# Site settings
title: Chaos Darmstadt e.V.
tagline: Ihre verlässliche CCC-Vertretung in Südhessen
email: info@chaos-darmstadt.de
description: > # this means to ignore newlines until "baseurl:"
   Darmstädter Erfahrungs-Austauschkreis des Chaos Computer Club,
   Hackspace und Hochschulgruppe an der TU Darmstadt
baseurl: /
exclude: [vendor]
url: "https://chaos-darmstadt.de"

# Build settings
markdown: kramdown

permalink: ":year/:title.html"

sass:
    sass_dir: _sass
    style: :compressed

nav_links:
    left:
        News: '/'
        CCC-ErfA: '/ccc-erfa.html'
        Hackspace: '/hackspace.html'
        Freifunk: '/freifunk.html'
        PyStaDa: '/pystada.html'
        C-Radar: '/c-radar.html'
    right:
        Wiki: 'https://wiki.chaos-darmstadt.de/'
        Kontakt: '/kontakt.html'
